### PR TITLE
Fix chart builder type and color

### LINKED ISSUE #5: Rendering Issues with Pie & Doughnut Charts
## _Who_ is the bug affecting?

Those who are using v1.1 of the LWC out of the box and trying to render pie & doughnut charts using SOQL queries or JSON strings from within the Lightning Page Builder.

## _How_ do we replicate the issue?

Drag LWCC onto a record page in Lightning Page Builder, select pie or doughnut as the chart type, and add a SOQL query or JSON dataset.

## Expected behavior (i.e. solution)

The charts render as colored bullseye rings instead of the traditional pieced charts. Upon trouble-shooting w/ team it seems to be because the labels aren't detected or associated with the values properly.

## Other Comments

Thank you again team :)

### PR DESCRIPTION
**Pull request by scolladon**
## Description

Chart builder had an issue in the way it build the data element.
It was silent for the line and bar chart and reproducible with the pie, radar and doughnut chart.

The solution involved a change in the way to create data component and in the way it gather the labels

/!\ Breaking change : Label in apex move from String type to List<String>. Every implementation of Custom ChartDataProvider are impacted. May create regression or trouble to upgrade the package

## Motivation and Context

This change improve the use cases of the chart builder

## How Has This Been Tested?

Jest test
Apex test
Deployment test
App Builder testing
In Sandbox testing

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue) fixes #5 
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by scolladon** [comment]
It seems there is no need to upgrade the documentation.
If you think otherwise please let me know, I'll do the modification

File: force-app/main/default/lwc/chartBuilder/chartBuilder.js [hunk 1]
```diff
@@ -129,13 +134,25 @@ export default class ChartBuilder extends LightningElement {
...
   isLoaded = false;
   error = false;
   stack;
 
   errorCallback(error, stack) {
     this.error = error;
     this.stack = stack;
+    this._details = null;
+    this._detailsLabels = null;
+    this.dimensionsLabels = null;
```
Comment (victorgz) [inline force-app/main/default/lwc/chartBuilder/chartBuilder.js:155]: 👍

File: force-app/main/default/classes/ChartDataProviderTest.cls [hunk 2]
```diff
@@ -46,14 +46,14 @@ public class ChartDataProviderTest {
...
-      aChartData.label = TEST_LABEL;
+      aChartData.labels = TEST_LABEL;
       aChartData.detail = TEST_DATA;
       aChartData.bgColor = TEST_COLOR;
       chartDatas.add(aChartData);
       return chartDatas;
     }
   }
-  public static final String TEST_LABEL = 'test';
+  public static final List<String> TEST_LABEL = new List<String>{ 'test' };
```
Comment (victorgz) [inline force-app/main/default/classes/ChartDataProviderTest.cls:56]: Small detail: what about renaming the TEST_LABEL constant to TEST_LABELS (in plural) as now it is a list instead of a String ?

File: force-app/main/default/lwc/chartBuilder/chartBuilder.html [hunk 3]
```diff
@@ -35,7 +35,7 @@
           <template if:false={isRadial}>
             <c-cartesian-linear-axis
               axis="y"
-              ticks-beginatzero="true"
+              tick-beginatzero="true"
```
Comment (victorgz) [inline force-app/main/default/lwc/chartBuilder/chartBuilder.html:38]: Nice catch! We totally missed it last time

**Review by victorgz — APPROVED** [review]

**Comment by scolladon** [comment]
fix #5

File: force-app/main/default/lwc/chartBuilder/chartBuilder.js [hunk 4]
```diff
@@ -129,13 +134,25 @@ export default class ChartBuilder extends LightningElement {
     return [POLARAREA_CHART_TYPE, RADAR_CHART_TYPE].includes(this.type);
   }
 
+  get isDimensionable() {
+    return [
```
Comment (pmdartus) [inline force-app/main/default/lwc/chartBuilder/chartBuilder.js:138]: You can extract this array to avoid having to recreate it every time you invoke the getter.
Otherwise, you can just do a plain `===` check with `||`, this will be even faster.

**Review by pmdartus — APPROVED** [review]
I have a small nitpick, otherwise, the code looks good.

**Review by victorgz — APPROVED** [review]
